#!/usr/bin/env python3
"""Generate ``ErdosStraus/Finite.lean``: the finite Erdős–Straus certificate.

The witness table is produced by the P11 module
``bemyself/experiments/erdos_straus.py`` (the canonical lexicographically
smallest witness per ``n``, deterministic); every row is re-checked here with
exact ``fractions.Fraction`` arithmetic before anything is emitted, so a bug
in the search cannot end up in the Lean file unnoticed. The digest recorded in
the emitted header is the sha256 of the P11 module's stdout for the same
limit — the same value a reader gets from
``python3 -m bemyself.experiments.erdos_straus <limit> | sha256sum``.

The emitted file contains

* ``witnesses`` — the table as ``(n, a, b, c)`` tuples, ascending in ``n``,
* ``witnesses_all_ok`` — one kernel ``decide`` over the whole table,
* ``finite_bridge`` — for every ``n`` with ``2 ≤ n ≤ limit`` an explicit
  witness, proved case by case (``interval_cases``, then ``ok_sound`` with a
  kernel ``decide`` per case).

Usage:

    python3 lean/erdos-straus/tools/gen_witnesses.py [limit]

The repository root is put on ``sys.path`` by this script, so any working
directory works. Regeneration is deterministic: the same limit yields
byte-identical output.
"""

from __future__ import annotations

import hashlib
import io
import sys
from fractions import Fraction
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from bemyself.experiments import erdos_straus  # noqa: E402

LIMIT = 1000
OUT = Path(__file__).resolve().parent.parent / "ErdosStraus" / "Finite.lean"


def rows(limit):
    """``[(n, a, b, c)]`` for ``n = 2..limit``, exact-checked."""
    spf = erdos_straus.smallest_prime_factors(2 * limit)
    out = []
    for n in range(2, limit + 1):
        triple = erdos_straus.witness(n, spf)
        if triple is None:
            raise SystemExit(f"gap at n = {n}: no witness found, refusing to emit")
        a, b, c = triple
        if Fraction(4, n) != Fraction(1, a) + Fraction(1, b) + Fraction(1, c):
            raise SystemExit(f"exact rational check failed at n = {n}: {triple}")
        out.append((n, a, b, c))
    return out


def artifact(limit):
    """The P11 stdout for ``limit`` and its sha256."""
    buf = io.StringIO()
    if erdos_straus.run(limit, buf) != 0:
        raise SystemExit(f"P11 run reported gaps for limit {limit}")
    text = buf.getvalue()
    return text, hashlib.sha256(text.encode()).hexdigest()


def parse_artifact(text):
    """The ``n a b c`` rows of the P11 stdout as tuples."""
    out = []
    for line in text.splitlines():
        parts = line.split()
        if len(parts) == 4 and all(part.isdigit() for part in parts):
            out.append(tuple(int(part) for part in parts))
    return out


def render(data, limit, digest):
    header = f"""/-
  GENERATED by lean/erdos-straus/tools/gen_witnesses.py — do not edit.

  Witness table for the finite window 2 ≤ n ≤ {limit}, computed with
  bemyself/experiments/erdos_straus.py (P11) and re-checked with exact
  Fraction arithmetic at generation time. sha256 of the P11 stdout for
  n = 2..{limit} (reproduce with
  `python3 -m bemyself.experiments.erdos_straus {limit} | sha256sum`):

  {digest}
-/
import ErdosStraus.Basic

-- The generated table and the {limit - 1}-way case split are long terms; the
-- default elaborator recursion limit (1000) is too low for them.
set_option maxRecDepth 100000

namespace ErdosStraus

/-- The witness table, ascending in `n`: canonical lexicographically smallest
witness `(a, b, c)` for every `n` in `[2, {limit}]`. The literal is emitted in
chunks of 100 (`++`-joined) so no single term gets deep. -/
def witnesses : List (ℕ × ℕ × ℕ × ℕ) :=
"""
    chunk_size = 100
    body = []
    for start in range(0, len(data), chunk_size):
        part = data[start:start + chunk_size]
        body.append("  [\n")
        for index, (n, a, b, c) in enumerate(part):
            comma = "" if index + 1 == len(part) else ","
            body.append(f"    ({n}, {a}, {b}, {c}){comma}\n")
        body.append("  ]")
        body.append("\n" if start + chunk_size >= len(data) else " ++\n")
    middle = f"""
/-- One kernel `decide` over the whole table: every row passes `ok`. -/
theorem witnesses_all_ok : witnesses.all (fun ⟨n, a, b, c⟩ => ok n a b c) = true := by
  decide

/-- Finite bridge: every `n` with `2 ≤ n ≤ {limit}` has an explicit witness.
The {limit - 1} cases are enumerated by `interval_cases`; each case is closed
by its row's triple and a kernel `decide` of the cross-multiplied witness
condition, lifted to the rational identity by `ok_sound`. -/
theorem finite_bridge (n : ℕ) (hn2 : 2 ≤ n) (hnN : n ≤ {limit}) :
    ∃ a b c : ℕ, 0 < a ∧ 0 < b ∧ 0 < c ∧ (4 : ℚ) / n = 1 / a + 1 / b + 1 / c := by
  interval_cases n
"""
    cases = []
    for _, a, b, c in data:
        cases.append(f"  · exact ⟨{a}, {b}, {c}, ok_sound (by decide) (by decide)⟩\n")
    return header + "".join(body) + middle + "".join(cases) + "\nend ErdosStraus\n"


def main(argv=None):
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) > 1:
        print("usage: gen_witnesses.py [limit]", file=sys.stderr)
        return 2
    limit = int(args[0]) if args else LIMIT
    if limit < 2:
        print("usage: gen_witnesses.py [limit]: limit must be >= 2", file=sys.stderr)
        return 2
    data = rows(limit)
    text, digest = artifact(limit)
    if parse_artifact(text) != data:
        raise SystemExit("table and P11 artifact disagree — refusing to emit")
    OUT.write_text(render(data, limit, digest), encoding="utf-8")
    print(f"wrote {OUT} ({len(data)} rows, limit {limit})")
    print(f"P11 stdout sha256: {digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
